#!/bin/bash
# Regenerate windows/version.rc from the VERSION file. Run before windres.
# Keeps FILEVERSION/PRODUCTVERSION and the string versions in lockstep with
# the single source of truth (VERSION), so release bumps touch one file.
set -euo pipefail
REPO="$(cd "$(dirname "$0")/.." && pwd)"
cd "$REPO"
V="$(tr -d '[:space:]' < VERSION)"
[[ "$V" =~ ^([0-9]+)\.([0-9]+)\.([0-9]+) ]] || { echo "bad VERSION: $V" >&2; exit 1; }
MAJOR="${BASH_REMATCH[1]}" MINOR="${BASH_REMATCH[2]}" PATCH="${BASH_REMATCH[3]}"

cat > windows/version.rc <<EOF
// GENERATED by scripts/gen-windows-version-rc.sh — do not edit by hand.
// Windows version metadata for bridgesessions.exe (Explorer Properties,
// GetFileVersionInfo). App/product name is "Bridge Sessions"; the executable
// stays bridgesessions.exe (CLI alias bs).
#include <winver.h>

1 VERSIONINFO
FILEVERSION     ${MAJOR},${MINOR},${PATCH},0
PRODUCTVERSION  ${MAJOR},${MINOR},${PATCH},0
FILEOS          VOS_NT_WINDOWS32
FILETYPE        VFT_APP
BEGIN
  BLOCK "StringFileInfo"
  BEGIN
    BLOCK "040904B0"
    BEGIN
      VALUE "CompanyName",      "Mind-Dragon"
      VALUE "FileDescription",  "Bridge Sessions"
      VALUE "FileVersion",      "${V}"
      VALUE "InternalName",     "bridgesessions"
      VALUE "LegalCopyright",   "Copyright (c) Mind-Dragon"
      VALUE "OriginalFilename", "bridgesessions.exe"
      VALUE "ProductName",      "Bridge Sessions"
      VALUE "ProductVersion",   "${V}"
    END
  END
  BLOCK "VarFileInfo"
  BEGIN
    VALUE "Translation", 0x0409, 1200
  END
END
EOF
echo "wrote windows/version.rc for ${V}"
