#!/usr/bin/env python3
"""Generate docs/cli.md from the binary's own --help output.

Documentation that is written by hand drifts from the CLI. This reads the real
help text, so the reference cannot disagree with the shipped binary.

    python3 scripts/gen-cli-docs.py > docs/cli.md
    python3 scripts/gen-cli-docs.py --check      # exit 1 if docs are stale
"""
from __future__ import annotations

import argparse
import os
import re
import subprocess
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def find_binary() -> str:
    # Prefer the newest usable build so a stale tree cannot generate stale docs.
    cands: list[str] = []
    if os.environ.get("BRIDGESESSIONS_BINARY"):
        cands.append(os.environ["BRIDGESESSIONS_BINARY"])
    for sub in ("test", "linux-x86_64", "macos-arm64", "windows-x86_64", ""):
        cands.append(os.path.join(REPO, "build", sub, "bridgesessions"))
    for name in ("bridgesessions", "bs"):
        for d in os.environ.get("PATH", "").split(os.pathsep):
            cands.append(os.path.join(d, name))
    best, best_mtime = None, -1.0
    for cand in cands:
        if cand and os.path.isfile(cand) and os.access(cand, os.X_OK):
            mt = os.path.getmtime(cand)
            if mt > best_mtime:
                best, best_mtime = cand, mt
    if best:
        return best
    sys.exit("error: no bridgesessions binary found; build first or set BRIDGESESSIONS_BINARY")


def wrap(text: str, width: int = 96) -> str:
    """Collapse CLI11's wrapped help into sentence-case prose."""
    text = re.sub(r"\s+", " ", text).strip()
    return text


def parse_subcommands(help_text: str) -> list[tuple[str, str]]:
    idx = help_text.find("SUBCOMMANDS:")
    if idx < 0:
        return []
    out: list[tuple[str, str]] = []
    cur: list | None = None
    for line in help_text[idx:].split("\n")[1:]:
        m = re.match(r"^  ([a-z][a-z0-9-]*)\s{2,}(.*)$", line)
        if m:
            if cur:
                out.append((cur[0], wrap(cur[1])))
            cur = [m.group(1), m.group(2)]
        elif cur is not None and line.strip():
            cur[1] += " " + line.strip()
    if cur:
        out.append((cur[0], wrap(cur[1])))
    return out


def parse_options(help_text: str) -> list[tuple[str, str]]:
    idx = help_text.find("OPTIONS:")
    if idx < 0:
        return []
    tail = help_text[idx:]
    stop = tail.find("SUBCOMMANDS:")
    if stop >= 0:
        tail = tail[:stop]
    out: list[tuple[str, str]] = []
    cur: list | None = None
    for line in tail.split("\n")[1:]:
        if not line.strip():
            continue
        # CLI11 pads the description to a fixed column, and a flag list such as
        # "-h,     --help" contains runs of spaces itself, so split on every
        # long run and rejoin all but the last as the flag list.
        parts = re.split(r"\s{3,}", line.strip())
        if len(parts) >= 2 and parts[0].startswith("-"):
            if cur:
                out.append((wrap(cur[0]), wrap(cur[1])))
            cur = [re.sub(r"\s+", " ", " ".join(parts[:-1])).strip(), parts[-1]]
        elif cur is not None and not line.strip().startswith("-"):
            cur[1] += " " + line.strip()
    if cur:
        out.append((wrap(cur[0]), wrap(cur[1])))
    return out


def run_help(binary: str, args: list[str]) -> str:
    p = subprocess.run([binary, *args, "--help"], capture_output=True, text=True)
    return p.stdout or p.stderr


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="exit 1 if docs/cli.md differs from generated output")
    ap.add_argument("-o", "--output", default=os.path.join(REPO, "docs", "cli.md"))
    opts = ap.parse_args()

    binary = find_binary()
    version = subprocess.run([binary, "--version"], capture_output=True,
                             text=True).stdout.strip()
    root_help = run_help(binary, [])

    top_usage = ""
    for line in root_help.split("\n"):
        if "--config" in line and "bridgesessions" in line:
            top_usage = line.strip()
            break

    lines: list[str] = []
    w = lines.append
    w("# Command reference")
    w("")
    w("<!-- GENERATED by scripts/gen-cli-docs.py — do not edit by hand. -->")
    w(f"<!-- Source: `{os.path.basename(binary)} --help`, version {version} -->")
    w("")
    w("Every command the binary accepts, in the order the CLI lists them.")
    w("Regenerate after changing the CLI:")
    w("")
    w("```bash")
    w("python3 scripts/gen-cli-docs.py > docs/cli.md")
    w("```")
    w("")
    w("## Usage")
    w("")
    w("```")
    w("bs [OPTIONS] [PEER] [SESSION] [SUBCOMMANDS]")
    w("```")
    w("")
    w("`PEER` alone attaches to (or starts) a session on that peer. `PEER` plus")
    w("`SESSION` reattaches to a named session. With no arguments on an interactive")
    w("terminal you get the fleet selector; with `--daemon` you get the relay daemon.")
    w("")

    top_opts = parse_options(root_help)
    if top_opts:
        w("## Global options")
        w("")
        w("| Option | Description |")
        w("|---|---|")
        for flag, desc in top_opts:
            w(f"| `{flag}` | {desc.replace('|', chr(92) + '|')} |")
        w("")

    subs = parse_subcommands(root_help)
    subs = [(n, d) for n, d in subs if d != "internal: per-session PTY worker"]
    w(f"## Commands ({len(subs)})")
    w("")
    w("| Command | Description |")
    w("|---|---|")
    for name, desc in subs:
        first = desc.split(". ")[0]
        if not first.endswith("."):
            first += "."
        w(f"| [`{name}`](#{name}) | {first.replace('|', chr(92) + '|')} |")
    w("")

    for name, _ in subs:
        sub_help = run_help(binary, [name])
        sub_usage = ""
        for line in sub_help.split("\n"):
            if line.strip().startswith("bridgesessions") and name in line:
                sub_usage = line.strip()
                break
        w(f"### {name}")
        w("")
        if sub_usage:
            w("```")
            w(sub_usage.replace("bridgesessions", "bs"))
            w("```")
            w("")
        body = run_help(binary, [name])
        opt = parse_options(body)
        if opt:
            w("| Option | Description |")
            w("|---|---|")
            for flag, desc in opt:
                if "Print this help" in desc:
                    continue
                w(f"| `{flag}` | {desc.replace('|', chr(92) + '|')} |")
            w("")
        subsubs = parse_subcommands(body)
        if subsubs:
            for sname, sdesc in subsubs:
                w(f"**`{name} {sname}`** — {sdesc}")
                w("")

    text = "\n".join(lines).rstrip() + "\n"

    if opts.check:
        try:
            with open(opts.output, encoding="utf-8") as fh:
                current = fh.read()
        except FileNotFoundError:
            print(f"error: {opts.output} is missing", file=sys.stderr)
            return 1
        if current != text:
            print(f"error: {opts.output} is stale; "
                  f"run python3 scripts/gen-cli-docs.py > {opts.output}",
                  file=sys.stderr)
            return 1
        print(f"{opts.output} is up to date")
        return 0

    sys.stdout.write(text)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
