# BridgeSessions one-line install + upgrade (Windows PowerShell)
#
#   irm https://codeberg.org/Mind-Dragon/BridgeSessions/raw/tag/26.08.06-beta1/scripts/install.ps1 | iex
#

$ErrorActionPreference = "Stop"
$TAG = if ($env:BRIDGESESSIONS_TAG) { $env:BRIDGESESSIONS_TAG } else { "26.08.06-beta1" }
$BASE = "https://codeberg.org/Mind-Dragon/BridgeSessions/raw/tag/$TAG/dist"
$INSTALL_DIR = "$env:LOCALAPPDATA\bridgesessions"
$BIN_PATH = "$INSTALL_DIR\bridgesessions.exe"
$VERSION_FILE = "$INSTALL_DIR\.bridgesessions-version"
$CONFIG_DIR = "$env:USERPROFILE\.bridgesessions"
$CONFIG_PATH = "$CONFIG_DIR\config"

# -- 1. DETECT AND KILL ALL RUNNING DAEMONS (including Session 0) ------------
$wasRunning = $false
try {
    # Get-CimInstance finds processes across ALL sessions (Session 0 phantoms
    # are invisible to Get-Process from WinRM but hold IPC port 19980).
    $procs = Get-CimInstance Win32_Process -Filter "Name like '%bridgesessions%'" -ErrorAction SilentlyContinue
    if ($procs) {
        $wasRunning = $true
        foreach ($p in $procs) {
            Write-Host "→ Killing bridgesessions PID $($p.ProcessId) (Session $($p.SessionId))..."
            try { Stop-Process -Id $p.ProcessId -Force -ErrorAction SilentlyContinue } catch {}
        }
        Start-Sleep -Seconds 2
    }
} catch {}

# Also kill via taskkill as fallback
try { taskkill /f /im bridgesessions.exe 2>$null } catch {}
Start-Sleep -Seconds 1

# -- 3. DOWNLOAD + INSTALL ---------------------------------------------------
New-Item -ItemType Directory -Force -Path $INSTALL_DIR | Out-Null

$CURRENT = ""
if (Test-Path $VERSION_FILE) { $CURRENT = Get-Content $VERSION_FILE }

$needsDownload = $true
if ($CURRENT -eq $TAG -and (Test-Path $BIN_PATH)) {
    Write-Host "→ bridgesessions $TAG already installed."
    $needsDownload = $false
}

if ($needsDownload) {
    $URL = "$BASE/bridgesessions-windows-x86_64.exe"
    Write-Host "→ Downloading bridgesessions $TAG for Windows..."
    Invoke-WebRequest -Uri $URL -OutFile $BIN_PATH
    $TAG | Set-Content $VERSION_FILE
    Write-Host "→ Download complete."
}

# -- 4. VALIDATE -------------------------------------------------------------
$ver = & $BIN_PATH --version 2>&1
Write-Host "→ Version: $ver"

# -- 5. APP DIRS + DEFAULT CONFIG + CLEANUP -----------------------------------
$RECEIVE_DIR = "$CONFIG_DIR\received"
New-Item -ItemType Directory -Force -Path $CONFIG_DIR | Out-Null
New-Item -ItemType Directory -Force -Path $RECEIVE_DIR | Out-Null

# Clean received/ dir if it has too many files (prevents daemon crash from
# binary files triggering JSON parse errors — known macOS/Windows issue)
$receiveFiles = Get-ChildItem -Path $RECEIVE_DIR -File -ErrorAction SilentlyContinue
if ($receiveFiles.Count -gt 50) {
    Write-Host "→ Cleaning $($receiveFiles.Count) files from received/ (prevents daemon crash)..."
    Remove-Item -Path "$RECEIVE_DIR\*" -Force -ErrorAction SilentlyContinue
}

if (-not (Test-Path $CONFIG_PATH)) {
    Write-Host "→ Creating default config at $CONFIG_PATH..."
    $nodeName = $env:COMPUTERNAME
    $configContent = @"
# BridgeSessions config — generated by install.ps1
node.name $nodeName
node.listen 0.0.0.0:19949
receive_dir $RECEIVE_DIR
"@
    $configContent | Set-Content -Path $CONFIG_PATH -Encoding ASCII
}

# -- 6. ADD TO PATH ----------------------------------------------------------
$userPath = [Environment]::GetEnvironmentVariable("Path", "User")
if ($userPath -notlike "*$INSTALL_DIR*") {
    Write-Host "→ Adding $INSTALL_DIR to PATH..."
    [Environment]::SetEnvironmentVariable("Path", "$userPath;$INSTALL_DIR", "User")
    $env:Path = "$env:Path;$INSTALL_DIR"
}

# -- 7. SCHEDULED TASK: DAEMON -----------------------------------------------
$daemonAction = New-ScheduledTaskAction -Execute $BIN_PATH -Argument "--config `"$CONFIG_PATH`""
$daemonTrigger = New-ScheduledTaskTrigger -AtStartup
$daemonSettings = New-ScheduledTaskSettingsSet -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries -StartWhenAvailable -RestartCount 3 -RestartInterval (New-TimeSpan -Minutes 1)

$daemonTask = Get-ScheduledTask -TaskName "BridgeSessions" -ErrorAction SilentlyContinue
if ($daemonTask) {
    Write-Host "→ Updating existing BridgeSessions scheduled task..."
    Set-ScheduledTask -TaskName "BridgeSessions" -Action $daemonAction -Trigger $daemonTrigger -Settings $daemonSettings | Out-Null
} else {
    Write-Host "→ Creating BridgeSessions scheduled task..."
    try {
        Register-ScheduledTask -TaskName "BridgeSessions" -Action $daemonAction -Trigger $daemonTrigger -Settings $daemonSettings -RunLevel Highest -Force | Out-Null
    } catch {
        Write-Host "→ Could not register daemon task with elevated privileges. Trying schtasks..."
        schtasks /create /tn "BridgeSessions" /tr "`"$BIN_PATH`" --config `"$CONFIG_PATH`"" /sc onstart /ru SYSTEM /f 2>$null
    }
}
Write-Host "→ Daemon scheduled task installed (BridgeSessions)."

# -- 8. SCHEDULED TASK: CUA HELPER -------------------------------------------
$cuaAction = New-ScheduledTaskAction -Execute $BIN_PATH -Argument "--config `"$CONFIG_PATH`" --cua-helper"
$cuaTrigger = New-ScheduledTaskTrigger -AtLogOn
$cuaSettings = New-ScheduledTaskSettingsSet -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries

$cuaTask = Get-ScheduledTask -TaskName "BridgeSessions-CuaHelper" -ErrorAction SilentlyContinue
if ($cuaTask) {
    Write-Host "→ Updating existing BridgeSessions-CuaHelper scheduled task..."
    Set-ScheduledTask -TaskName "BridgeSessions-CuaHelper" -Action $cuaAction -Trigger $cuaTrigger -Settings $cuaSettings | Out-Null
} else {
    Write-Host "→ Creating BridgeSessions-CuaHelper scheduled task..."
    try {
        Register-ScheduledTask -TaskName "BridgeSessions-CuaHelper" -Action $cuaAction -Trigger $cuaTrigger -Settings $cuaSettings -User $env:USERNAME -Force | Out-Null
    } catch {
        Write-Host "→ Could not register CUA helper task. Trying schtasks..."
        schtasks /create /tn "BridgeSessions-CuaHelper" /tr "`"$BIN_PATH`" --config `"$CONFIG_PATH`" --cua-helper" /sc onlogon /ru $env:USERNAME /f 2>$null
    }
}
Write-Host "→ CUA helper scheduled task installed (BridgeSessions-CuaHelper)."

# -- 9. ALWAYS START DAEMON ----------------------------------------------------
Write-Host "→ Starting daemon..."
Start-ScheduledTask -TaskName "BridgeSessions" -ErrorAction SilentlyContinue
Start-Sleep -Seconds 2
try {
    $newProcs = Get-CimInstance Win32_Process -Filter "Name like '%bridgesessions%'" -ErrorAction SilentlyContinue
    $daemonProc = $newProcs | Where-Object { $_.CommandLine -like "*--config*" -and $_.CommandLine -notlike "*--cua-helper*" } | Select-Object -First 1
    if ($daemonProc) {
        Write-Host "→ Daemon running (PID $($daemonProc.ProcessId))."
    } else {
        Write-Host "→ WARNING: Daemon did not start. Run manually:"
        Write-Host "   $BIN_PATH --config `"$CONFIG_PATH`""
    }
} catch {
    Write-Host "→ WARNING: Could not verify daemon status."
}

Write-Host "→ Done."
