# BridgeSessions one-line install + upgrade (Windows PowerShell)
#
#   irm https://codeberg.org/Mind-Dragon/BridgeSessions/raw/tag/26.08.06-beta1/scripts/install.ps1 | iex
#

$ErrorActionPreference = "Stop"
$TAG = if ($env:BRIDGESESSIONS_TAG) { $env:BRIDGESESSIONS_TAG } else { "26.08.06-beta1" }
$BASE = "https://codeberg.org/Mind-Dragon/BridgeSessions/raw/tag/$TAG/dist"
$INSTALL_DIR = "$env:LOCALAPPDATA\bridgesessions"
$BIN_PATH = "$INSTALL_DIR\bridgesessions.exe"
$VERSION_FILE = "$INSTALL_DIR\.bridgesessions-version"
$CONFIG_DIR = "$env:USERPROFILE\.bridgesessions"
$CONFIG_PATH = "$CONFIG_DIR\config"

# -- 1. DETECT RUNNING DAEMON ------------------------------------------------
$wasRunning = $false
$existingPid = $null
try {
    $proc = Get-Process -Name bridgesessions -ErrorAction SilentlyContinue
    if ($proc) {
        $wasRunning = $true
        $existingPid = $proc.Id
        Write-Host "→ bridgesessions daemon running (PID $existingPid) — will restart after upgrade."
    }
} catch {}

# -- 2. STOP DAEMON ----------------------------------------------------------
if ($wasRunning) {
    Write-Host "→ Stopping daemon..."
    try { taskkill /f /im bridgesessions.exe 2>$null } catch {}
    Start-Sleep -Seconds 2
}

# -- 3. DOWNLOAD + INSTALL ---------------------------------------------------
New-Item -ItemType Directory -Force -Path $INSTALL_DIR | Out-Null

$CURRENT = ""
if (Test-Path $VERSION_FILE) { $CURRENT = Get-Content $VERSION_FILE }

$needsDownload = $true
if ($CURRENT -eq $TAG -and (Test-Path $BIN_PATH)) {
    Write-Host "→ bridgesessions $TAG already installed."
    $needsDownload = $false
}

if ($needsDownload) {
    $URL = "$BASE/bridgesessions-windows-x86_64.exe"
    Write-Host "→ Downloading bridgesessions $TAG for Windows..."
    Invoke-WebRequest -Uri $URL -OutFile $BIN_PATH
    $TAG | Set-Content $VERSION_FILE
    Write-Host "→ Download complete."
}

# -- 4. VALIDATE -------------------------------------------------------------
$ver = & $BIN_PATH --version 2>&1
Write-Host "→ Version: $ver"

# -- 5. APP DIRS + DEFAULT CONFIG --------------------------------------------
$RECEIVE_DIR = "$CONFIG_DIR\received"
New-Item -ItemType Directory -Force -Path $CONFIG_DIR | Out-Null
New-Item -ItemType Directory -Force -Path $RECEIVE_DIR | Out-Null

if (-not (Test-Path $CONFIG_PATH)) {
    Write-Host "→ Creating default config at $CONFIG_PATH..."
    $nodeName = $env:COMPUTERNAME
    $configContent = @"
# BridgeSessions config — generated by install.ps1
node.name $nodeName
node.listen 0.0.0.0:19949
receive_dir $RECEIVE_DIR
"@
    $configContent | Set-Content -Path $CONFIG_PATH -Encoding ASCII
}

# -- 6. ADD TO PATH ----------------------------------------------------------
$userPath = [Environment]::GetEnvironmentVariable("Path", "User")
if ($userPath -notlike "*$INSTALL_DIR*") {
    Write-Host "→ Adding $INSTALL_DIR to PATH..."
    [Environment]::SetEnvironmentVariable("Path", "$userPath;$INSTALL_DIR", "User")
    $env:Path = "$env:Path;$INSTALL_DIR"
}

# -- 7. SCHEDULED TASK: DAEMON -----------------------------------------------
$daemonAction = New-ScheduledTaskAction -Execute $BIN_PATH -Argument "--config `"$CONFIG_PATH`""
$daemonTrigger = New-ScheduledTaskTrigger -AtStartup
$daemonSettings = New-ScheduledTaskSettingsSet -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries -StartWhenAvailable -RestartCount 3 -RestartInterval (New-TimeSpan -Minutes 1)

$daemonTask = Get-ScheduledTask -TaskName "BridgeSessions" -ErrorAction SilentlyContinue
if ($daemonTask) {
    Write-Host "→ Updating existing BridgeSessions scheduled task..."
    Set-ScheduledTask -TaskName "BridgeSessions" -Action $daemonAction -Trigger $daemonTrigger -Settings $daemonSettings | Out-Null
} else {
    Write-Host "→ Creating BridgeSessions scheduled task..."
    try {
        Register-ScheduledTask -TaskName "BridgeSessions" -Action $daemonAction -Trigger $daemonTrigger -Settings $daemonSettings -RunLevel Highest -Force | Out-Null
    } catch {
        Write-Host "→ Could not register daemon task with elevated privileges. Trying schtasks..."
        schtasks /create /tn "BridgeSessions" /tr "`"$BIN_PATH`" --config `"$CONFIG_PATH`"" /sc onstart /ru SYSTEM /f 2>$null
    }
}
Write-Host "→ Daemon scheduled task installed (BridgeSessions)."

# -- 8. SCHEDULED TASK: CUA HELPER -------------------------------------------
$cuaAction = New-ScheduledTaskAction -Execute $BIN_PATH -Argument "--config `"$CONFIG_PATH`" --cua-helper"
$cuaTrigger = New-ScheduledTaskTrigger -AtLogOn
$cuaSettings = New-ScheduledTaskSettingsSet -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries

$cuaTask = Get-ScheduledTask -TaskName "BridgeSessions-CuaHelper" -ErrorAction SilentlyContinue
if ($cuaTask) {
    Write-Host "→ Updating existing BridgeSessions-CuaHelper scheduled task..."
    Set-ScheduledTask -TaskName "BridgeSessions-CuaHelper" -Action $cuaAction -Trigger $cuaTrigger -Settings $cuaSettings | Out-Null
} else {
    Write-Host "→ Creating BridgeSessions-CuaHelper scheduled task..."
    try {
        Register-ScheduledTask -TaskName "BridgeSessions-CuaHelper" -Action $cuaAction -Trigger $cuaTrigger -Settings $cuaSettings -User $env:USERNAME -Force | Out-Null
    } catch {
        Write-Host "→ Could not register CUA helper task. Trying schtasks..."
        schtasks /create /tn "BridgeSessions-CuaHelper" /tr "`"$BIN_PATH`" --config `"$CONFIG_PATH`" --cua-helper" /sc onlogon /ru $env:USERNAME /f 2>$null
    }
}
Write-Host "→ CUA helper scheduled task installed (BridgeSessions-CuaHelper)."

# -- 9. RESTART DAEMON (if it was running) ------------------------------------
if ($wasRunning) {
    Write-Host "→ Restarting daemon..."
    Start-ScheduledTask -TaskName "BridgeSessions" -ErrorAction SilentlyContinue
    Start-Sleep -Seconds 2
    try {
        $newProc = Get-Process -Name bridgesessions -ErrorAction SilentlyContinue
        if ($newProc) {
            Write-Host "→ Daemon restarted (PID $($newProc.Id))."
        } else {
            Write-Host "→ WARNING: Daemon did not start. Run manually:"
            Write-Host "   $BIN_PATH --config $CONFIG_PATH"
        }
    } catch {
        Write-Host "→ Starting daemon silently..."
    }
}

Write-Host "→ Done."
