#!/usr/bin/env bash
set -eu
# BridgeSessions one-line install (Linux / macOS)
#
#   curl -fsSL https://codeberg.org/Mind-Dragon/BridgeSessions/raw/tag/26.08.06-beta1/scripts/install.sh | bash
#
# Or join a mesh in one command:
#
#   curl ... | bash -s -- join <host-addr> <invite-code>
#
# On Windows (PowerShell):
#   Invoke-WebRequest -Uri "https://codeberg.org/Mind-Dragon/BridgeSessions/raw/tag/26.08.06-beta1/dist/bridgesessions-windows-x86_64.exe" -OutFile "$env:LOCALAPPDATA\bridgesessions.exe"

TAG="${BRIDGESESSIONS_TAG:-26.08.06-beta1}"
BASE="https://codeberg.org/Mind-Dragon/BridgeSessions/raw/tag/${TAG}/dist"
INSTALL_DIR="${HOME}/.local/bin"
VERSION_FILE="${INSTALL_DIR}/.bridgesessions-version"

os=$(uname -s)
arch=$(uname -m)
case "${os}-${arch}" in
  Linux-x86_64)
    BIN="bridgesessions-linux-x86_64"
    BIN_NAME="bridgesessions"
    ;;
  Darwin-arm64)
    BIN="bridgesessions-macos-arm64"
    BIN_NAME="bridgesessions"
    ;;
  *)
    echo "Unsupported platform: ${os}-${arch}" >&2
    echo "On Windows, download manually:" >&2
    echo "  ${BASE}/bridgesessions-windows-x86_64.exe" >&2
    exit 1
    ;;
esac

mkdir -p "${INSTALL_DIR}"

validate_binary() {
  candidate=$1
  if ! command -v file >/dev/null 2>&1; then
    echo "ERROR: 'file' is required to validate the downloaded artifact" >&2
    return 1
  fi
  description=$(file -b "${candidate}")
  case "${os}-${arch}" in
    Linux-x86_64)
      echo "${description}" | grep -qE '^ELF 64-bit LSB.*x86-64' || {
        echo "ERROR: downloaded artifact is not a Linux x86-64 ELF executable: ${description}" >&2
        return 1
      }
      ;;
    Darwin-arm64)
      echo "${description}" | grep -qE '^Mach-O 64-bit.*arm64' || {
        echo "ERROR: downloaded artifact is not a macOS arm64 Mach-O executable: ${description}" >&2
        return 1
      }
      ;;
  esac
}

CURRENT=""
[ -f "${VERSION_FILE}" ] && CURRENT="$(cat "${VERSION_FILE}")" || true
if [ "${CURRENT}" = "${TAG}" ] && [ -x "${INSTALL_DIR}/${BIN_NAME}" ]; then
  validate_binary "${INSTALL_DIR}/${BIN_NAME}"
  echo "→ bridgesessions ${TAG} already installed."
else
  echo "→ Downloading bridgesessions ${TAG} for ${os}-${arch}..."
  TMP_BIN="${INSTALL_DIR}/.${BIN_NAME}.download.$$"
  trap 'rm -f "${TMP_BIN:-}"' EXIT INT TERM
  curl -fsSL --progress-bar "${BASE}/${BIN}" -o "${TMP_BIN}"
  chmod +x "${TMP_BIN}"
  validate_binary "${TMP_BIN}"

  # SHA-256 checksum verification
  TMP_SUMS="${INSTALL_DIR}/.SHA256SUMS.$$"
  curl -fsSL "${BASE}/SHA256SUMS" -o "${TMP_SUMS}" 2>/dev/null || true
  if [ -f "${TMP_SUMS}" ]; then
    EXPECTED_HASH=$(grep " ${BIN}\$" "${TMP_SUMS}" | awk '{print $1}')
    if [ -n "${EXPECTED_HASH}" ]; then
      ACTUAL_HASH=$(sha256sum "${TMP_BIN}" 2>/dev/null | awk '{print $1}' || shasum -a 256 "${TMP_BIN}" | awk '{print $1}')
      if [ "${ACTUAL_HASH}" != "${EXPECTED_HASH}" ]; then
        echo "ERROR: SHA-256 mismatch!" >&2
        echo "  expected: ${EXPECTED_HASH}" >&2
        echo "  actual:   ${ACTUAL_HASH}" >&2
        rm -f "${TMP_BIN}" "${TMP_SUMS}"
        exit 1
      fi
      echo "→ SHA-256 verified."
    fi
  else
    echo "→ WARNING: could not download SHA256SUMS — skipping checksum verification." >&2
  fi
  rm -f "${TMP_SUMS}"

  REPORTED_VERSION=$("${TMP_BIN}" --version)
  EXPECTED_VERSION=${TAG#v}
  if [ "${REPORTED_VERSION}" != "${EXPECTED_VERSION}" ]; then
    echo "ERROR: downloaded binary reports ${REPORTED_VERSION}; expected ${EXPECTED_VERSION}" >&2
    exit 1
  fi
  mv -f "${TMP_BIN}" "${INSTALL_DIR}/${BIN_NAME}"
  echo "${TAG}" > "${VERSION_FILE}"
  trap - EXIT INT TERM
fi

"${INSTALL_DIR}/${BIN_NAME}" --version

if ! echo "${PATH}" | grep -q "${INSTALL_DIR}"; then
  echo "→ Add to PATH: export PATH=\"${INSTALL_DIR}:\$PATH\""
  echo "   (or restart your shell)"
fi

# ── App dirs + default config ──────────────────────────────────────
APP_HOME="${HOME}/.bridgesessions"
RECEIVE_DIR="${APP_HOME}/received"
mkdir -p "${APP_HOME}" "${RECEIVE_DIR}"

CONFIG_PATH="${APP_HOME}/config"
if [ ! -f "${CONFIG_PATH}" ]; then
  echo "→ Creating default config at ${CONFIG_PATH}..."
  HOSTNAME_SHORT="$(hostname -s 2>/dev/null || echo node)"
  cat > "${CONFIG_PATH}" <<EOF
# BridgeSessions config — generated by install.sh
node.name ${HOSTNAME_SHORT}
node.listen 0.0.0.0:19949
receive_dir ${RECEIVE_DIR}
EOF
  chmod 600 "${CONFIG_PATH}"
fi

# ── System service setup ───────────────────────────────────────────
BIN_ABS="${INSTALL_DIR}/${BIN_NAME}"
case "${os}" in
  Darwin)
    PLIST_DIR="${HOME}/Library/LaunchAgents"
    PLIST_PATH="${PLIST_DIR}/com.bridgesessions.mesh.plist"
    mkdir -p "${PLIST_DIR}"
    echo "→ Installing launchd service..."
    cat > "${PLIST_PATH}" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>com.bridgesessions.mesh</string>
  <key>ProgramArguments</key>
  <array>
    <string>${BIN_ABS}</string>
    <string>--config</string>
    <string>${CONFIG_PATH}</string>
  </array>
  <key>RunAtLoad</key>
  <true/>
  <key>KeepAlive</key>
  <true/>
  <key>StandardOutPath</key>
  <string>${APP_HOME}/daemon.log</string>
  <key>StandardErrorPath</key>
  <string>${APP_HOME}/daemon.err</string>
</dict>
</plist>
EOF
    launchctl bootstrap "gui/$(id -u)" "${PLIST_PATH}" 2>/dev/null || \
      launchctl load -w "${PLIST_PATH}" 2>/dev/null || true
    echo "→ launchd service installed (com.bridgesessions.mesh)."
    ;;
  Linux)
    UNIT_DIR="${HOME}/.config/systemd/user"
    UNIT_PATH="${UNIT_DIR}/bridgesessions.service"
    mkdir -p "${UNIT_DIR}"
    echo "→ Installing systemd user service..."
    cat > "${UNIT_PATH}" <<EOF
[Unit]
Description=BridgeSessions mesh daemon
After=network.target

[Service]
ExecStart=${BIN_ABS} --config ${CONFIG_PATH}
Restart=on-failure
RestartSec=3

[Install]
WantedBy=default.target
EOF
    systemctl --user daemon-reload 2>/dev/null || true
    systemctl --user enable bridgesessions.service 2>/dev/null || true
    systemctl --user start bridgesessions.service 2>/dev/null || true
    echo "→ systemd service installed (bridgesessions.service)."
    ;;
esac

# ── CUA helper instructions ────────────────────────────────────────
echo ""
echo "→ CUA helper (desktop automation):"
echo "   For screen capture + input injection on desktop sessions, run:"
echo "   ${BIN_ABS} --cua-helper &"
echo ""

# ── Join mode ──────────────────────────────────────────────────────
if [ $# -ge 2 ] && [ "$1" = "join" ]; then
  shift
  echo "→ Joining mesh: bridgesessions join $@ --start"
  exec "${INSTALL_DIR}/${BIN_NAME}" join "$@" --start
fi

echo "→ Ready."
echo "   To join a mesh, run:"
echo "   ${INSTALL_DIR}/${BIN_NAME} join <host-addr> <invite-code> --start"
